//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace sephp.Share.Locale {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sephp.Share.Locale.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 One‑click quick launch on the overview page 的本地化字符串。
        /// </summary>
        public static string AddQuickLaunchTips {
            get {
                return ResourceManager.GetString("AddQuickLaunchTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add to Quick Launch 的本地化字符串。
        /// </summary>
        public static string AddToQuickLaunch {
            get {
                return ResourceManager.GetString("AddToQuickLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add to System PATH 的本地化字符串。
        /// </summary>
        public static string AddToSystemPath {
            get {
                return ResourceManager.GetString("AddToSystemPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Once added, it will take effect permanently 的本地化字符串。
        /// </summary>
        public static string AddToSystemPathTips {
            get {
                return ResourceManager.GetString("AddToSystemPathTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apache 的本地化字符串。
        /// </summary>
        public static string Apache {
            get {
                return ResourceManager.GetString("Apache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SEPHP 的本地化字符串。
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Background Task 的本地化字符串。
        /// </summary>
        public static string BackgroundTask {
            get {
                return ResourceManager.GetString("BackgroundTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debug Mode 的本地化字符串。
        /// </summary>
        public static string DebugMode {
            get {
                return ResourceManager.GetString("DebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MySQL 的本地化字符串。
        /// </summary>
        public static string MySQL {
            get {
                return ResourceManager.GetString("MySQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nginx 的本地化字符串。
        /// </summary>
        public static string Nginx {
            get {
                return ResourceManager.GetString("Nginx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Overview 的本地化字符串。
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PHP 的本地化字符串。
        /// </summary>
        public static string PHP {
            get {
                return ResourceManager.GetString("PHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Redis 的本地化字符串。
        /// </summary>
        public static string Redis {
            get {
                return ResourceManager.GetString("Redis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reload 的本地化字符串。
        /// </summary>
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GitHub 的本地化字符串。
        /// </summary>
        public static string RepoName {
            get {
                return ResourceManager.GetString("RepoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restart 的本地化字符串。
        /// </summary>
        public static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting 的本地化字符串。
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other 的本地化字符串。
        /// </summary>
        public static string Setting_Other {
            get {
                return ResourceManager.GetString("Setting_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch Dark/Light mode 的本地化字符串。
        /// </summary>
        public static string SwitchDarkOrLightMode {
            get {
                return ResourceManager.GetString("SwitchDarkOrLightMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme 的本地化字符串。
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Website 的本地化字符串。
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
    }
}
